version: "3.3"
services:
  api:
    container_name: api
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
  db:
    container_name: db
    image: postgres:12.1
    environment:
      POSTGRES_DB: jvnm
    ports:
      - "5432:5432"